name: Node.js Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ec2-user
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy Hello World Node.js app
      run: node app.js
